# -*- coding: utf-8 -*-
# Каждое слово:
#   en          — английское слово/фраза (показывается на лёгком/среднем уровне)
#   ru          — перевод на русский
#   category    — "work" (закупки/стройка) или "everyday" (повседневная лексика)
#   sentence    — пример предложения на английском с пропуском "___"
#   sentence_ru — перевод примера предложения на русский
#   answer      — что именно нужно вписать в пропуск (для сложного уровня)
#   alt         — (необязательно) дополнительные допустимые синонимы перевода

WORD_BANK = [
    # ---------- РАБОЧАЯ ТЕМАТИКА: закупки / стройка ----------
    {"en": "supplier", "ru": "поставщик", "category": "work",
     "sentence": "We need to contact the ___ about the delivery delay.",
     "sentence_ru": "Нам нужно связаться с поставщиком по поводу задержки доставки.",
     "answer": "supplier"},
    {"en": "procurement", "ru": "закупки, снабжение", "category": "work",
     "sentence": "The ___ department approved the new budget.",
     "sentence_ru": "Отдел закупок одобрил новый бюджет.",
     "answer": "procurement"},
    {"en": "purchase order", "ru": "заказ на закупку", "category": "work",
     "alt": ["заявка на покупку"],
     "sentence": "Please send the signed ___ to the vendor today.",
     "sentence_ru": "Пожалуйста, отправьте подписанный заказ на закупку поставщику сегодня.",
     "answer": "purchase order"},
    {"en": "invoice", "ru": "счёт-фактура", "category": "work",
     "sentence": "The accountant is waiting for the ___ before payment.",
     "sentence_ru": "Бухгалтер ждёт счёт-фактуру перед оплатой.",
     "answer": "invoice"},
    {"en": "quotation", "ru": "коммерческое предложение", "category": "work",
     "sentence": "We received a good ___ from the supplier.",
     "sentence_ru": "Мы получили хорошее коммерческое предложение от поставщика.",
     "answer": "quotation"},
    {"en": "tender", "ru": "тендер", "category": "work",
     "sentence": "Our company decided to participate in the ___.",
     "sentence_ru": "Наша компания решила участвовать в тендере.",
     "answer": "tender"},
    {"en": "bid", "ru": "заявка, предложение цены", "category": "work",
     "sentence": "They submitted the lowest ___ for the project.",
     "sentence_ru": "Они подали самую низкую заявку на проект.",
     "answer": "bid"},
    {"en": "lead time", "ru": "срок поставки", "category": "work",
     "sentence": "The ___ for this material is about three weeks.",
     "sentence_ru": "Срок поставки этого материала — около трёх недель.",
     "answer": "lead time"},
    {"en": "bulk order", "ru": "оптовый заказ", "category": "work",
     "sentence": "We get a discount when placing a ___.",
     "sentence_ru": "Мы получаем скидку при оформлении оптового заказа.",
     "answer": "bulk order"},
    {"en": "delivery terms", "ru": "условия поставки", "category": "work",
     "sentence": "Let's clarify the ___ before signing the contract.",
     "sentence_ru": "Давайте уточним условия поставки перед подписанием контракта.",
     "answer": "delivery terms"},
    {"en": "shipment", "ru": "партия груза, отгрузка", "category": "work",
     "sentence": "The next ___ is expected to arrive on Friday.",
     "sentence_ru": "Следующая партия груза ожидается в пятницу.",
     "answer": "shipment"},
    {"en": "warehouse", "ru": "склад", "category": "work",
     "sentence": "The materials are stored in the main ___.",
     "sentence_ru": "Материалы хранятся на главном складе.",
     "answer": "warehouse"},
    {"en": "inventory", "ru": "складские запасы", "category": "work", "alt": ["инвентарь"],
     "sentence": "We need to check the ___ before ordering more.",
     "sentence_ru": "Нужно проверить складские запасы, прежде чем заказывать ещё.",
     "answer": "inventory"},
    {"en": "stock shortage", "ru": "дефицит на складе", "category": "work",
     "sentence": "There is a ___ of cement this month.",
     "sentence_ru": "В этом месяце дефицит цемента.",
     "answer": "shortage"},
    {"en": "contract terms", "ru": "условия договора", "category": "work",
     "sentence": "Both parties agreed on the ___.",
     "sentence_ru": "Обе стороны согласовали условия договора.",
     "answer": "contract terms"},
    {"en": "payment terms", "ru": "условия оплаты", "category": "work",
     "sentence": "The ___ require a 30% advance payment.",
     "sentence_ru": "Условия оплаты требуют аванс в размере 30%.",
     "answer": "payment terms"},
    {"en": "discount", "ru": "скидка", "category": "work",
     "sentence": "We negotiated a 10% ___ with the supplier.",
     "sentence_ru": "Мы договорились о скидке 10% с поставщиком.",
     "answer": "discount"},
    {"en": "wholesale price", "ru": "оптовая цена", "category": "work",
     "sentence": "Buying directly gives us the ___.",
     "sentence_ru": "Прямая закупка даёт нам оптовую цену.",
     "answer": "wholesale price"},
    {"en": "construction site", "ru": "строительная площадка", "category": "work",
     "sentence": "No visitors are allowed on the ___ without a helmet.",
     "sentence_ru": "На строительную площадку без каски посетители не допускаются.",
     "answer": "construction site"},
    {"en": "blueprint", "ru": "чертёж, план", "category": "work",
     "sentence": "The engineer updated the ___ yesterday.",
     "sentence_ru": "Инженер обновил чертёж вчера.",
     "answer": "blueprint"},
    {"en": "scaffolding", "ru": "строительные леса", "category": "work",
     "sentence": "Workers are installing ___ around the building.",
     "sentence_ru": "Рабочие устанавливают строительные леса вокруг здания.",
     "answer": "scaffolding"},
    {"en": "concrete", "ru": "бетон", "category": "work",
     "sentence": "The foundation is made of reinforced ___.",
     "sentence_ru": "Фундамент сделан из армированного бетона.",
     "answer": "concrete"},
    {"en": "rebar", "ru": "арматура", "category": "work",
     "sentence": "They ordered more ___ for the second floor.",
     "sentence_ru": "Они заказали больше арматуры для второго этажа.",
     "answer": "rebar"},
    {"en": "contractor", "ru": "подрядчик", "category": "work",
     "sentence": "We hired a new ___ for the roofing work.",
     "sentence_ru": "Мы наняли нового подрядчика для кровельных работ.",
     "answer": "contractor"},
    {"en": "subcontractor", "ru": "субподрядчик", "category": "work",
     "sentence": "The electrical work was done by a ___.",
     "sentence_ru": "Электромонтажные работы выполнил субподрядчик.",
     "answer": "subcontractor"},
    {"en": "building permit", "ru": "разрешение на строительство", "category": "work",
     "sentence": "We can't start until we get the ___.",
     "sentence_ru": "Мы не можем начать, пока не получим разрешение на строительство.",
     "answer": "building permit"},
    {"en": "heavy machinery", "ru": "тяжёлая техника", "category": "work",
     "sentence": "The site requires ___ to move the soil.",
     "sentence_ru": "На площадке нужна тяжёлая техника, чтобы перемещать грунт.",
     "answer": "heavy machinery"},
    {"en": "crane", "ru": "подъёмный кран", "category": "work",
     "sentence": "A ___ lifted the steel beams to the top.",
     "sentence_ru": "Подъёмный кран поднял стальные балки наверх.",
     "answer": "crane"},
    {"en": "deadline", "ru": "крайний срок", "category": "work",
     "sentence": "We must finish the report before the ___.",
     "sentence_ru": "Мы должны закончить отчёт до крайнего срока.",
     "answer": "deadline"},
    {"en": "to place an order", "ru": "разместить заказ", "category": "work",
     "sentence": "I need to ___ an order for more tiles today.",
     "sentence_ru": "Мне нужно разместить заказ на дополнительную плитку сегодня.",
     "answer": "place"},

    # ---------- ПОВСЕДНЕВНАЯ ЛЕКСИКА: слова, глаголы, действия ----------
    {"en": "to wake up", "ru": "просыпаться", "category": "everyday",
     "sentence": "I usually ___ up at seven in the morning.",
     "sentence_ru": "Обычно я просыпаюсь в семь утра.",
     "answer": "wake"},
    {"en": "to have breakfast", "ru": "завтракать", "category": "everyday",
     "sentence": "We always ___ breakfast together as a family.",
     "sentence_ru": "Мы всегда завтракаем вместе всей семьёй.",
     "answer": "have"},
    {"en": "to commute", "ru": "добираться до работы", "category": "everyday",
     "sentence": "It takes me an hour to ___ to the office.",
     "sentence_ru": "Мне требуется час, чтобы добраться до офиса.",
     "answer": "commute"},
    {"en": "to attend a meeting", "ru": "посещать встречу", "category": "everyday",
     "sentence": "I need to ___ a meeting at ten o'clock.",
     "sentence_ru": "Мне нужно посетить встречу в десять часов.",
     "answer": "attend"},
    {"en": "to run errands", "ru": "заниматься делами, поручениями", "category": "everyday",
     "sentence": "On Saturdays I usually ___ errands around the city.",
     "sentence_ru": "По субботам я обычно занимаюсь делами по городу.",
     "answer": "run"},
    {"en": "to relax", "ru": "отдыхать, расслабляться", "category": "everyday",
     "sentence": "After work I like to ___ on the sofa.",
     "sentence_ru": "После работы я люблю отдыхать на диване.",
     "answer": "relax"},
    {"en": "to fall asleep", "ru": "засыпать", "category": "everyday",
     "sentence": "I usually ___ asleep before eleven.",
     "sentence_ru": "Обычно я засыпаю до одиннадцати.",
     "answer": "fall"},
    {"en": "grocery store", "ru": "продуктовый магазин", "category": "everyday",
     "sentence": "I need to stop by the ___ after work.",
     "sentence_ru": "Мне нужно заехать в продуктовый магазин после работы.",
     "answer": "grocery store"},
    {"en": "traffic jam", "ru": "пробка на дороге", "category": "everyday",
     "sentence": "We were stuck in a ___ for an hour.",
     "sentence_ru": "Мы простояли в пробке час.",
     "answer": "traffic jam"},
    {"en": "neighbor", "ru": "сосед", "category": "everyday",
     "sentence": "My ___ helped me carry the boxes.",
     "sentence_ru": "Мой сосед помог мне нести коробки.",
     "answer": "neighbor"},
    {"en": "to borrow", "ru": "одалживать (брать)", "category": "everyday",
     "alt": ["заимствовать", "брать взаймы", "взять взаймы"],
     "sentence": "Can I ___ your pen for a minute?",
     "sentence_ru": "Можно одолжить твою ручку на минутку?",
     "answer": "borrow"},
    {"en": "to lend", "ru": "одалживать (давать)", "category": "everyday",
     "alt": ["давать взаймы", "одолжить"],
     "sentence": "Could you ___ me some money until Friday?",
     "sentence_ru": "Не мог бы ты одолжить мне немного денег до пятницы?",
     "answer": "lend"},
    {"en": "appointment", "ru": "запись, назначенная встреча", "category": "everyday",
     "sentence": "I have a doctor's ___ tomorrow morning.",
     "sentence_ru": "У меня завтра утром запись к врачу.",
     "answer": "appointment"},
    {"en": "to be in a hurry", "ru": "спешить", "category": "everyday",
     "sentence": "Sorry, I can't talk now, I'm in a ___.",
     "sentence_ru": "Извини, не могу говорить сейчас, я спешу.",
     "answer": "hurry"},
    {"en": "to take care of", "ru": "заботиться о ком-то/чём-то", "category": "everyday",
     "sentence": "She has to take ___ of her children today.",
     "sentence_ru": "Ей нужно позаботиться о своих детях сегодня.",
     "answer": "care"},
    {"en": "household chores", "ru": "домашние дела", "category": "everyday",
     "sentence": "We share the household ___ every weekend.",
     "sentence_ru": "Мы делим домашние дела каждые выходные.",
     "answer": "chores"},
    {"en": "to charge a phone", "ru": "заряжать телефон", "category": "everyday",
     "sentence": "I forgot to ___ my phone last night.",
     "sentence_ru": "Я забыл зарядить телефон вчера вечером.",
     "answer": "charge"},
    {"en": "weather forecast", "ru": "прогноз погоды", "category": "everyday",
     "sentence": "According to the ___, it will rain tomorrow.",
     "sentence_ru": "Согласно прогнозу погоды, завтра будет дождь.",
     "answer": "weather forecast"},
    {"en": "to get used to", "ru": "привыкать к чему-то", "category": "everyday",
     "sentence": "It took me a while to get ___ to the new schedule.",
     "sentence_ru": "Мне потребовалось время, чтобы привыкнуть к новому расписанию.",
     "answer": "used"},
    {"en": "to make a decision", "ru": "принимать решение", "category": "everyday",
     "sentence": "We need to make a ___ by tomorrow.",
     "sentence_ru": "Нам нужно принять решение до завтра.",
     "answer": "decision"},
    {"en": "to keep in touch", "ru": "поддерживать связь", "category": "everyday",
     "sentence": "Let's keep in ___ after the trip.",
     "sentence_ru": "Давай поддерживать связь после поездки.",
     "answer": "touch"},
    {"en": "to look forward to", "ru": "с нетерпением ждать", "category": "everyday",
     "sentence": "I look ___ to seeing you next week.",
     "sentence_ru": "Я с нетерпением жду встречи с тобой на следующей неделе.",
     "answer": "forward"},
    {"en": "to run out of", "ru": "заканчиваться (о запасах)", "category": "everyday",
     "sentence": "We ran out ___ milk this morning.",
     "sentence_ru": "У нас закончилось молоко сегодня утром.",
     "answer": "of"},
    {"en": "to be worth it", "ru": "стоить того", "category": "everyday",
     "sentence": "The trip was tiring but it was worth ___.",
     "sentence_ru": "Поездка была утомительной, но она того стоила.",
     "answer": "it"},
    {"en": "spare time", "ru": "свободное время", "category": "everyday",
     "sentence": "In my ___ time I like to read.",
     "sentence_ru": "В свободное время я люблю читать.",
     "answer": "spare"},
    {"en": "to pay attention", "ru": "обращать внимание", "category": "everyday",
     "sentence": "Please pay ___ to the instructions.",
     "sentence_ru": "Пожалуйста, обратите внимание на инструкции.",
     "answer": "attention"},
    {"en": "chore", "ru": "домашняя обязанность", "category": "everyday",
     "sentence": "Taking out the trash is my daily ___.",
     "sentence_ru": "Выносить мусор — моя ежедневная обязанность.",
     "answer": "chore"},
    {"en": "to catch up on", "ru": "наверстать упущенное", "category": "everyday",
     "sentence": "I need to catch ___ on some sleep this weekend.",
     "sentence_ru": "Мне нужно наверстать сон в эти выходные.",
     "answer": "up"},
    {"en": "to be exhausted", "ru": "быть измотанным", "category": "everyday",
     "sentence": "After the long day, I was completely ___.",
     "sentence_ru": "После долгого дня я был совершенно измотан.",
     "answer": "exhausted"},
    {"en": "to unwind", "ru": "расслабляться после напряжения", "category": "everyday",
     "sentence": "A walk in the park helps me ___ after work.",
     "sentence_ru": "Прогулка в парке помогает мне расслабиться после работы.",
     "answer": "unwind"},
]
