# -*- coding: utf-8 -*-
# Каждое слово:
#   en       — английское слово/фраза (показывается на лёгком/среднем уровне)
#   ru       — перевод на русский
#   category — "work" (закупки/стройка) или "everyday" (повседневная лексика)
#   sentence — пример предложения с пропуском "___" (для сложного уровня)
#   answer   — что именно нужно вписать в пропуск (для сложного уровня)

WORD_BANK = [
    # ---------- РАБОЧАЯ ТЕМАТИКА: закупки / стройка ----------
    {"en": "supplier", "ru": "поставщик", "category": "work",
     "sentence": "We need to contact the ___ about the delivery delay.", "answer": "supplier"},
    {"en": "procurement", "ru": "закупки, снабжение", "category": "work",
     "sentence": "The ___ department approved the new budget.", "answer": "procurement"},
    {"en": "purchase order", "ru": "заказ на закупку", "category": "work",
     "sentence": "Please send the signed ___ to the vendor today.", "answer": "purchase order"},
    {"en": "invoice", "ru": "счёт-фактура", "category": "work",
     "sentence": "The accountant is waiting for the ___ before payment.", "answer": "invoice"},
    {"en": "quotation", "ru": "коммерческое предложение", "category": "work",
     "sentence": "We received a good ___ from the supplier.", "answer": "quotation"},
    {"en": "tender", "ru": "тендер", "category": "work",
     "sentence": "Our company decided to participate in the ___.", "answer": "tender"},
    {"en": "bid", "ru": "заявка, предложение цены", "category": "work",
     "sentence": "They submitted the lowest ___ for the project.", "answer": "bid"},
    {"en": "lead time", "ru": "срок поставки", "category": "work",
     "sentence": "The ___ for this material is about three weeks.", "answer": "lead time"},
    {"en": "bulk order", "ru": "оптовый заказ", "category": "work",
     "sentence": "We get a discount when placing a ___.", "answer": "bulk order"},
    {"en": "delivery terms", "ru": "условия поставки", "category": "work",
     "sentence": "Let's clarify the ___ before signing the contract.", "answer": "delivery terms"},
    {"en": "shipment", "ru": "партия груза, отгрузка", "category": "work",
     "sentence": "The next ___ is expected to arrive on Friday.", "answer": "shipment"},
    {"en": "warehouse", "ru": "склад", "category": "work",
     "sentence": "The materials are stored in the main ___.", "answer": "warehouse"},
    {"en": "inventory", "ru": "складские запасы", "category": "work", "alt": ["инвентарь"],
     "sentence": "We need to check the ___ before ordering more.", "answer": "inventory"},
    {"en": "stock shortage", "ru": "дефицит на складе", "category": "work",
     "sentence": "There is a ___ of cement this month.", "answer": "shortage"},
    {"en": "contract terms", "ru": "условия договора", "category": "work",
     "sentence": "Both parties agreed on the ___.", "answer": "contract terms"},
    {"en": "payment terms", "ru": "условия оплаты", "category": "work",
     "sentence": "The ___ require a 30% advance payment.", "answer": "payment terms"},
    {"en": "discount", "ru": "скидка", "category": "work",
     "sentence": "We negotiated a 10% ___ with the supplier.", "answer": "discount"},
    {"en": "wholesale price", "ru": "оптовая цена", "category": "work",
     "sentence": "Buying directly gives us the ___.", "answer": "wholesale price"},
    {"en": "construction site", "ru": "строительная площадка", "category": "work",
     "sentence": "No visitors are allowed on the ___ without a helmet.", "answer": "construction site"},
    {"en": "blueprint", "ru": "чертёж, план", "category": "work",
     "sentence": "The engineer updated the ___ yesterday.", "answer": "blueprint"},
    {"en": "scaffolding", "ru": "строительные леса", "category": "work",
     "sentence": "Workers are installing ___ around the building.", "answer": "scaffolding"},
    {"en": "concrete", "ru": "бетон", "category": "work",
     "sentence": "The foundation is made of reinforced ___.", "answer": "concrete"},
    {"en": "rebar", "ru": "арматура", "category": "work",
     "sentence": "They ordered more ___ for the second floor.", "answer": "rebar"},
    {"en": "contractor", "ru": "подрядчик", "category": "work",
     "sentence": "We hired a new ___ for the roofing work.", "answer": "contractor"},
    {"en": "subcontractor", "ru": "субподрядчик", "category": "work",
     "sentence": "The electrical work was done by a ___.", "answer": "subcontractor"},
    {"en": "building permit", "ru": "разрешение на строительство", "category": "work",
     "sentence": "We can't start until we get the ___.", "answer": "building permit"},
    {"en": "heavy machinery", "ru": "тяжёлая техника", "category": "work",
     "sentence": "The site requires ___ to move the soil.", "answer": "heavy machinery"},
    {"en": "crane", "ru": "подъёмный кран", "category": "work",
     "sentence": "A ___ lifted the steel beams to the top.", "answer": "crane"},
    {"en": "deadline", "ru": "крайний срок", "category": "work",
     "sentence": "We must finish the report before the ___.", "answer": "deadline"},
    {"en": "to place an order", "ru": "разместить заказ", "category": "work",
     "sentence": "I need to ___ an order for more tiles today.", "answer": "place"},

    # ---------- ПОВСЕДНЕВНАЯ ЛЕКСИКА: слова, глаголы, действия ----------
    {"en": "to wake up", "ru": "просыпаться", "category": "everyday",
     "sentence": "I usually ___ up at seven in the morning.", "answer": "wake"},
    {"en": "to have breakfast", "ru": "завтракать", "category": "everyday",
     "sentence": "We always ___ breakfast together as a family.", "answer": "have"},
    {"en": "to commute", "ru": "добираться до работы", "category": "everyday",
     "sentence": "It takes me an hour to ___ to the office.", "answer": "commute"},
    {"en": "to attend a meeting", "ru": "посещать встречу", "category": "everyday",
     "sentence": "I need to ___ a meeting at ten o'clock.", "answer": "attend"},
    {"en": "to run errands", "ru": "заниматься делами, поручениями", "category": "everyday",
     "sentence": "On Saturdays I usually ___ errands around the city.", "answer": "run"},
    {"en": "to relax", "ru": "отдыхать, расслабляться", "category": "everyday",
     "sentence": "After work I like to ___ on the sofa.", "answer": "relax"},
    {"en": "to fall asleep", "ru": "засыпать", "category": "everyday",
     "sentence": "I usually ___ asleep before eleven.", "answer": "fall"},
    {"en": "grocery store", "ru": "продуктовый магазин", "category": "everyday",
     "sentence": "I need to stop by the ___ after work.", "answer": "grocery store"},
    {"en": "traffic jam", "ru": "пробка на дороге", "category": "everyday",
     "sentence": "We were stuck in a ___ for an hour.", "answer": "traffic jam"},
    {"en": "neighbor", "ru": "сосед", "category": "everyday",
     "sentence": "My ___ helped me carry the boxes.", "answer": "neighbor"},
    {"en": "to borrow", "ru": "одалживать (брать)", "category": "everyday",
     "alt": ["заимствовать", "брать взаймы", "взять взаймы"],
     "sentence": "Can I ___ your pen for a minute?", "answer": "borrow"},
    {"en": "to lend", "ru": "одалживать (давать)", "category": "everyday",
     "alt": ["давать взаймы", "одолжить"],
     "sentence": "Could you ___ me some money until Friday?", "answer": "lend"},
    {"en": "appointment", "ru": "запись, назначенная встреча", "category": "everyday",
     "sentence": "I have a doctor's ___ tomorrow morning.", "answer": "appointment"},
    {"en": "to be in a hurry", "ru": "спешить", "category": "everyday",
     "sentence": "Sorry, I can't talk now, I'm in a ___.", "answer": "hurry"},
    {"en": "to take care of", "ru": "заботиться о ком-то/чём-то", "category": "everyday",
     "sentence": "She has to take ___ of her children today.", "answer": "care"},
    {"en": "household chores", "ru": "домашние дела", "category": "everyday",
     "sentence": "We share the household ___ every weekend.", "answer": "chores"},
    {"en": "to charge a phone", "ru": "заряжать телефон", "category": "everyday",
     "sentence": "I forgot to ___ my phone last night.", "answer": "charge"},
    {"en": "weather forecast", "ru": "прогноз погоды", "category": "everyday",
     "sentence": "According to the ___, it will rain tomorrow.", "answer": "weather forecast"},
    {"en": "to get used to", "ru": "привыкать к чему-то", "category": "everyday",
     "sentence": "It took me a while to get ___ to the new schedule.", "answer": "used"},
    {"en": "to make a decision", "ru": "принимать решение", "category": "everyday",
     "sentence": "We need to make a ___ by tomorrow.", "answer": "decision"},
    {"en": "to keep in touch", "ru": "поддерживать связь", "category": "everyday",
     "sentence": "Let's keep in ___ after the trip.", "answer": "touch"},
    {"en": "to look forward to", "ru": "с нетерпением ждать", "category": "everyday",
     "sentence": "I look ___ to seeing you next week.", "answer": "forward"},
    {"en": "to run out of", "ru": "заканчиваться (о запасах)", "category": "everyday",
     "sentence": "We ran out ___ milk this morning.", "answer": "of"},
    {"en": "to be worth it", "ru": "стоить того", "category": "everyday",
     "sentence": "The trip was tiring but it was worth ___.", "answer": "it"},
    {"en": "spare time", "ru": "свободное время", "category": "everyday",
     "sentence": "In my ___ time I like to read.", "answer": "spare"},
    {"en": "to pay attention", "ru": "обращать внимание", "category": "everyday",
     "sentence": "Please pay ___ to the instructions.", "answer": "attention"},
    {"en": "chore", "ru": "домашняя обязанность", "category": "everyday",
     "sentence": "Taking out the trash is my daily ___.", "answer": "chore"},
    {"en": "to catch up on", "ru": "наверстать упущенное", "category": "everyday",
     "sentence": "I need to catch ___ on some sleep this weekend.", "answer": "up"},
    {"en": "to be exhausted", "ru": "быть измотанным", "category": "everyday",
     "sentence": "After the long day, I was completely ___.", "answer": "exhausted"},
    {"en": "to unwind", "ru": "расслабляться после напряжения", "category": "everyday",
     "sentence": "A walk in the park helps me ___ after work.", "answer": "unwind"},
]
